### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by fpronto** [tristanls/dynamodb-lock-client#20]
Before starting with my problem i just want to thank you for this code

There is a way to use this as a browser package?

Right now i solved the "problem" with dynamodb.DocumentClient dependecy by injecting a middleware created by me.

But still I can't use this in a browser because of Joi depedency.

Someone had this problem before, or know a way to work arround this?

**Comment by tristanls** [comment]
Hi @fpronto , I just published [v0.5.3](https://github.com/tristanls/dynamodb-lock-client/releases/tag/v0.5.3) which according to [joi-browser](https://github.com/jeffbski/joi-browser) should be browser-compatible.
