### ISSUE TITLE
Latest release, lock acquired timestamp missing?

### ISSUE THREAD

**Issue by simlu** [tristanls/dynamodb-lock-client#29]
See this pr: https://github.com/blackflux/dy-alchemy/pull/1295/files

The following is no longer sent:
```json
        "lockAcquiredTimeUnixMs": {	
          "N": "1893448800000"	
        }
```

Not sure why this changed, but most importantly, how can we still check if the lock as expired without that information?

**Comment by tristanls** [comment]
Thank you. This was an error in code refactoring. Corrected as of [v0.7.2](https://github.com/tristanls/dynamodb-lock-client/releases/tag/v0.7.2).

**Comment by simlu** [comment]
Sweet, can confirm that the request signature changed again and is now as expected.

Closing this

**Comment by tristanls** [comment]
Thank you for the confirmation.
