### ISSUE TITLE
Tests Question

### ISSUE THREAD

**Issue by wootencl** [tristanls/dynamodb-lock-client#3]
@tristanls First of all really great library and appreciate the time/effort you've put into it. Source is fairly easy to follow and seems to accomplish exactly what's needed for locking (for my scenario at least). Have two quick questions for when you get a moment:

(1) Is the reason for the lack of tests because of the experimental state that the module is currently in, or a lack of time to implement?
(2) If it's a lack of time, do you have a preferred JS testing setup? 

Asking as I'm thinking about using this module for a distributed system I'm working on currently and would be willing to write tests. Having some CI&D/testing to ensure no breakage between releases is fairly important to me.

**Comment by tristanls** [comment]
Hey @wootencl , thank you for the interest!

To answer your question, primary reason for no tests is me not taking the time to implement tests. I tested manually to make sure things worked, and usage uncovered one bug so far #1 , so once I had confidence in present state and I haven't been changing the code, I never came back and shared that confidence via tests.

I agree with you that tests are important to ensure things continue to work as expected, especially if there's going to be continued development.

My preferred JS testing setup changes as new things come out. Lately I've been using [Jest](https://facebook.github.io/jest/) unit tests. 

If you're gonna take the time to add testing, feel free to pick whatever you like. Maybe I'll learn something. On the other hand, if you're looking for an example of testing, [this repo](https://github.com/tristanls/read-through-s3-decrypting-memory-cache) has my latest testing setup.

Cheers!

Tristan

**Comment by wootencl** [comment]
@tristanls Thanks for the prompt reply! Jest looks interesting. Haven't used it before but I recently wrote a React app that will also need tests so I may just bite the bullet and go that route. 

On a related topic, would you be opposed to introducing Travis CI for CI&D?

**Comment by tristanls** [comment]
I'm not opposed to Travis CI.

**Comment by wootencl** [comment]
@tristanls Thanks for the quick replies. After some additional research/requirements gathering I came to the conclusion that I may need to hand roll my implementation instead of using an off the shelf solution. Your module has given me great inspiration though on how I intend on laying out my work so thanks again for the effort you've put into it 🙂 .

**Comment by tristanls** [comment]
Glad the patterns here are useful. (^_^ ) 

Thanks for closing out the thread and best of luck!
