### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by simlu** [tristanls/dynamodb-lock-client#37]
Just wanted to give a big thank you for creating this library!

We've finally moved on to [our own locking logic](https://github.com/blackflux/aws-sdk-wrap/blob/master/src/module/dy/lock-manager.js), which is purpose build for our (much simpler) needs, but this library has gotten us here and we're very grateful for it!

It's an awesome library, especially since it handles various locking needs and has a good amount of features.

Thank you again, and so long, and thanks for all the ~fish~ code. I'm sure I'll see you around @tristanls =)

**Comment by tristanls** [comment]
Thanks @simlu ! I'm glad it lasted this long 😄. Cheers!
